name: jaappalante
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.5 
  

  flutter_localizations:
    sdk: flutter
  hexcolor: ^3.0.1  # Gardez la dernière version ici
  hexcolorname: ^0.0.9 
  get: ^4.6.6 # Ajout de la dépendance Get
  flutter_svg: ^2.0.15
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  change_app_package_name: ^1.4.0
  firebase_core: ^3.10.0
  google_nav_bar: ^5.0.7
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
   - assets/images/ # Répertoire des images
