// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9tvqOi375Yp_nBYj2GLS2iWCuOKFcaM',
    appId: '1:798924436033:web:632994c07b7857f36cccc0',
    messagingSenderId: '798924436033',
    projectId: 'jappalante-685ee',
    authDomain: 'jappalante-685ee.firebaseapp.com',
    storageBucket: 'jappalante-685ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvIJxHmf8Xicx-lkc8fX0acxhyIkEs34',
    appId: '1:798924436033:android:22ff3542cb81ee4e6cccc0',
    messagingSenderId: '798924436033',
    projectId: 'jappalante-685ee',
    storageBucket: 'jappalante-685ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0FTFPUs7w7iCzPr5L8BW37u_ZVGbNaE',
    appId: '1:798924436033:ios:018eb9516928a07c6cccc0',
    messagingSenderId: '798924436033',
    projectId: 'jappalante-685ee',
    storageBucket: 'jappalante-685ee.firebasestorage.app',
    iosBundleId: 'com.example.jaappalante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0FTFPUs7w7iCzPr5L8BW37u_ZVGbNaE',
    appId: '1:798924436033:ios:018eb9516928a07c6cccc0',
    messagingSenderId: '798924436033',
    projectId: 'jappalante-685ee',
    storageBucket: 'jappalante-685ee.firebasestorage.app',
    iosBundleId: 'com.example.jaappalante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9tvqOi375Yp_nBYj2GLS2iWCuOKFcaM',
    appId: '1:798924436033:web:7ad9d6375e4d177b6cccc0',
    messagingSenderId: '798924436033',
    projectId: 'jappalante-685ee',
    authDomain: 'jappalante-685ee.firebaseapp.com',
    storageBucket: 'jappalante-685ee.firebasestorage.app',
  );
}
